### PR TITLE
Features/prettyprint

### PR DESCRIPTION
**Pull request by shanliyu**

### CODE REVIEW

**Comment by zilu0907** [comment]
LGTM. 
In style.scss, I deleted the breakpoint for max-width(instead, implemented it in webstart.js), so this is a conflict that you may want to solve when merge.

**Comment by shanliyu** [comment]
> LGTM.
> In style.scss, I deleted the breakpoint for max-width(instead, implemented it in webstart.js), so this is a conflict that you may want to solve when merge.

@zilu0907 Can you point me to where you did this? I did not see any breakpoints being removed from your PR

EDIT: Nvm. I see it in webstart.ts. Thanks!

**Comment by zilu0907** [comment]
https://github.com/shanliyu/chocopy-wasm-compiler/blob/73d1c87a3bf8029528a2ce7d4789a7ddb9891683/style.scss#L157

**Comment by shanliyu** [comment]
> https://github.com/shanliyu/chocopy-wasm-compiler/blob/73d1c87a3bf8029528a2ce7d4789a7ddb9891683/style.scss#L157

Thanks!

**Pull request merged**
